services:
  - type: web
    name: ai-caption-app
    runtime: python
    plan: free
    pythonVersion: 3.10.13
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0
